require 'huginn_agent'

#HuginnAgent.load 'huginn_twilio_conversation_webhook_agent/concerns/my_agent_concern'
HuginnAgent.register 'huginn_twilio_conversation_webhook_agent/twilio_conversation_webhook_agent'
